# Generated by Django 3.2.9 on 2022-09-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
